import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

// To:Do
// Usar a paleta do luma

// ThemeData lightMode = ThemeData(
//   fontFamily: GoogleFonts.poppins().fontFamily,
//   colorScheme: ColorScheme.light(
//     primary: const Color(0xFF2190A4),
//     onPrimary: const Color(0xFFF5F5F5),
//     onSecondary: const Color(0xFF2E3133),
//     secondary: const Color.fromARGB(255, 183, 214, 220),
//     error: Colors.red.shade200,
//     onError: Colors.black,
//     surface: const Color(0xFFfafafa),
//     onSurface: const Color(0xFF2E3133),

//     surfaceContainer: const Color(0xFFEDEDED)
//   ),
// );

ThemeData lightMode = ThemeData(
  textTheme: TextTheme(),
  useMaterial3: true,
  fontFamily: GoogleFonts.poppins().fontFamily,
  splashColor: Colors.transparent,
  highlightColor: Colors.transparent,
  disabledColor: const Color(0xFFDADBDF),
  focusColor: const Color(0xFF212A40).withValues(alpha: 0.12),
  hoverColor: const Color(0xFF212A40).withValues(alpha: 0.06),
  colorScheme: ColorScheme(
    brightness: Brightness.light,
      primary: Color(0xff405f90),
      surfaceTint: Color(0xff405f90),
      onPrimary: Color(0xffffffff),
      primaryContainer: Color(0xffd6e3ff),
      onPrimaryContainer: Color(0xff264777),
      secondary: Color(0xff405f90),
      onSecondary: Color(0xffffffff),
      secondaryContainer: Color(0xffd6e3ff),
      onSecondaryContainer: Color(0xff274777),
      tertiary: Color(0xff00687b),
      onTertiary: Color(0xffffffff),
      tertiaryContainer: Color(0xffafecff),
      onTertiaryContainer: Color(0xff004e5d),
      error: Color(0xffba1a1a),
      onError: Color(0xffffffff),
      errorContainer: Color(0xffffdad6),
      onErrorContainer: Color(0xff93000a),
      // surface: Color(0xfff9f9ff),
      surface: Colors.white,
      onSurface: Color(0xff191c20),
      onSurfaceVariant: Color(0xff43474e),
      outline: Color(0xff74777f),
      outlineVariant: Color(0xffc4c6cf),
      shadow: Color(0xff000000),
      scrim: Color(0xff000000),
      inverseSurface: Color(0xff2e3035),
      inversePrimary: Color(0xffa9c7ff),
      primaryFixed: Color(0xffd6e3ff),
      onPrimaryFixed: Color(0xff001b3d),
      primaryFixedDim: Color(0xffa9c7ff),
      onPrimaryFixedVariant: Color(0xff264777),
      secondaryFixed: Color(0xffd6e3ff),
      onSecondaryFixed: Color(0xff001b3d),
      secondaryFixedDim: Color(0xffa9c7ff),
      onSecondaryFixedVariant: Color(0xff274777),
      tertiaryFixed: Color(0xffafecff),
      onTertiaryFixed: Color(0xff001f26),
      tertiaryFixedDim: Color(0xff85d2e8),
      onTertiaryFixedVariant: Color(0xff004e5d),
      surfaceDim: Color(0xffd9d9e0),
      surfaceBright: Color(0xfff9f9ff),
      surfaceContainerLowest: Color(0xffffffff),
      surfaceContainerLow: Color(0xfff3f3fa),
      surfaceContainer: Color(0xffF5F5F5),
      surfaceContainerHigh: Color(0xffF5F5F5),
      surfaceContainerHighest: Color(0xffF5F5F5),
  ),
);